\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Anisotropic Diffusion Limited Aggregates},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Anisotropic Diffusion Limited Aggregates}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\begin{figure}
\centering
\includegraphics{http://web.csulb.edu/~tgredig/research/fractal/fractal-example.png}
\caption{Exmample of isotropic diffusion aggregate fractal}
\end{figure}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Inspired by the M.S. thesis defense talk of Felix Arroyo with Galen
Pickett, here we explore fractals of aggregates. The aggregates are
simulated (generated) and then evaluated. Diffusion or random walk is
used to move the particles, once moved, they will be stationary. The
motion or diffusion is varied.

\hypertarget{dimension-of-fractals}{%
\subsection{Dimension of Fractals}\label{dimension-of-fractals}}

The dimension of a fractal can be computed in different ways. One way is
called the ``boxing method''. It covers an image of size \(N_1\) with
boxes of size \(N_1/\epsilon\), where \(\epsilon\) is the scaling
factor. Then it counts the number of boxes \(N_\epsilon\) it needs to
cover the original image. The following illustrations shows an
application of this method on the map of UK.

\begin{figure}
\centering
\includegraphics{https://upload.wikimedia.org/wikipedia/commons/2/28/Great_Britain_Box.svg}
\caption{Boxing method applied to UK map from Wikipedia}
\end{figure}

According to
\href{https://en.wikipedia.org/wiki/Minkowski\%E2\%80\%93Bouligand_dimension}{Wikipedia:Minkowski-Bouligand}
the dimension \(D_0\) can be computed as such:

\[ D_0 = lim_{\epsilon \rightarrow 0} \frac{\log(N_\epsilon)}{\log(1/\epsilon)} \]
Note that the dimenions is obtained in the limit, where
\(\epsilon \rightarrow 0\), which means that the box size then is small.
For a quick check of 2D, take a solid area \(A = \epsilon^2\), then
\(N_\epsilon = \epsilon^2\), so
\(D_0 = 2\log(\epsilon)/(-log(\epsilon)) = -2\). (Hmm, minus sign
issue!). Easily, can be shown for a line, or cube, see
\protect\hyperlink{Appendix}{Appendix}.

\hypertarget{generating-fractals}{%
\subsection{Generating Fractals}\label{generating-fractals}}

Create a box of dimension \(N_1\), then put a particle in the middle,
now add particles from the top or from the left. We are using periodic
boundary conditions, so left and right is the same, and top and bottom
is the same.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# loading default functions}
\KeywordTok{library}\NormalTok{(sp)}
\KeywordTok{source}\NormalTok{(}\StringTok{'func.fractals.R'}\NormalTok{) }
\NormalTok{N1 =}\StringTok{ }\DecValTok{80}
\NormalTok{l1 =}\StringTok{ }\KeywordTok{generate.fractal}\NormalTok{(N1)}
\end{Highlighting}
\end{Shaded}

\hypertarget{random-walk}{%
\subsection{Random Walk}\label{random-walk}}

As particles are added, the random walk length, or number of steps,
\(L\) until it hits the aggregate gets shorter as can see by this graph;
it does not fit to an exponential that well (hmm, can be investigated).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{n.particle =} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(l1[[}\DecValTok{4}\NormalTok{]]), }\DataTypeTok{L =}\NormalTok{l1[[}\DecValTok{4}\NormalTok{]])}
\NormalTok{d =}\StringTok{ }\NormalTok{d[d}\OperatorTok{$}\NormalTok{L}\OperatorTok{>}\DecValTok{0}\NormalTok{,]  }\CommentTok{# remove 0s}
\KeywordTok{ggplot}\NormalTok{(d, }\KeywordTok{aes}\NormalTok{(n.particle, L)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{col=}\StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_log10}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_smooth}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess'
\end{verbatim}

\includegraphics{report.fractal-dimensions_files/figure-latex/unnamed-chunk-2-1.pdf}

For a \href{https://en.wikipedia.org/wiki/Random_walk}{random walk}, we
estimate that the walking distance is proportional to
\(\propto \sqrt{L}\), where \(L\) is the number of steps. The blue line
indicates the size of the box.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\KeywordTok{sqrt}\NormalTok{(d}\OperatorTok{$}\NormalTok{L), }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{pch=}\DecValTok{20}\NormalTok{)}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{h=}\NormalTok{N1, }\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{,}\DataTypeTok{lwd=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{report.fractal-dimensions_files/figure-latex/unnamed-chunk-3-1.pdf}

\hypertarget{fractals-images}{%
\subsection{Fractals Images}\label{fractals-images}}

It took 4.08 seconds to generate this fractal with length 80x80. The
height in the graph corresponds to the number of particle added; i.e.~it
is time, the higher the later in time. A contrast was added, so the
first particle is not 1, but rather the contrast number.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(raster)}
\NormalTok{q =}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\KeywordTok{file.path}\NormalTok{(path.results,}\KeywordTok{paste}\NormalTok{(l1[[}\DecValTok{2}\NormalTok{]],}\StringTok{'.csv'}\NormalTok{,}\DataTypeTok{sep=}\StringTok{''}\NormalTok{)))}
\NormalTok{q =}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(q)}
\KeywordTok{plot}\NormalTok{(}\KeywordTok{raster}\NormalTok{(q))}
\end{Highlighting}
\end{Shaded}

\includegraphics{report.fractal-dimensions_files/figure-latex/unnamed-chunk-4-1.pdf}

Now, we will compute its dimensions using the boxing algorithm.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{l2 =}\StringTok{ }\KeywordTok{get.fractal.dimension.boxing}\NormalTok{(q)}
\CommentTok{# returns Ne vs. e and fit}
\NormalTok{d =}\StringTok{ }\NormalTok{l2[[}\StringTok{'result'}\NormalTok{]]}
\KeywordTok{ggplot}\NormalTok{(d, }\KeywordTok{aes}\NormalTok{(e.inv.log, Ne.log)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{col=}\StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{'log (1/'}\NormalTok{,epsilon,}\StringTok{')'}\NormalTok{))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{'log (N'}\NormalTok{[epsilon],}\StringTok{')'}\NormalTok{))) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_x_continuous}\NormalTok{(}\DataTypeTok{limits=}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{4}\NormalTok{,}\DecValTok{0}\NormalTok{)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{limits=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{6}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{report.fractal-dimensions_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit1 =}\StringTok{ }\NormalTok{l2[[}\StringTok{'fit'}\NormalTok{]]}
\KeywordTok{summary}\NormalTok{(fit1)}\OperatorTok{$}\NormalTok{coef}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Estimate Std. Error    t value     Pr(>|t|)
## (Intercept)  0.3335916 0.10110965   3.299305 3.135451e-03
## e.inv.log   -1.3540666 0.03973236 -34.079692 3.426125e-21
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"Dimension of fractal:"}\NormalTok{,}\KeywordTok{signif}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit1)}\OperatorTok{$}\NormalTok{coeff[}\DecValTok{2}\NormalTok{],}\DecValTok{3}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Dimension of fractal: -1.35"
\end{verbatim}

So, the dimension is \(D_0\) = -1.35 \(\pm\) 0.04.

\hypertarget{anisotropy}{%
\subsection{Anisotropy}\label{anisotropy}}

Adding anisotropy to the drift now. In the random walk the new particle
can move into 1 of 8 neighboring squares; the anisotropy is added by
generating more random numbers in one particular direction (positive),
the particle, then tends to move more into that direction.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# the higher the anistropy, the more it will move in one direction}
\NormalTok{l1 =}\StringTok{ }\KeywordTok{generate.fractal}\NormalTok{(N1, }\DataTypeTok{N.anisotropy=}\DecValTok{2}\NormalTok{, }\DataTypeTok{flip.FACTOR=}\DecValTok{1}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(}\KeywordTok{raster}\NormalTok{(l1[[}\StringTok{'q'}\NormalTok{]]))}
\end{Highlighting}
\end{Shaded}

\includegraphics{report.fractal-dimensions_files/figure-latex/unnamed-chunk-6-1.pdf}

Now, we will compute its dimensions using the boxing algorithm.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{l2 =}\StringTok{ }\KeywordTok{get.fractal.dimension.boxing}\NormalTok{(q)}
\NormalTok{fit2 =}\StringTok{ }\NormalTok{l2[[}\StringTok{'fit'}\NormalTok{]]}
\KeywordTok{summary}\NormalTok{(fit2)}\OperatorTok{$}\NormalTok{coef}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Estimate Std. Error    t value     Pr(>|t|)
## (Intercept)  0.3335916 0.10110965   3.299305 3.135451e-03
## e.inv.log   -1.3540666 0.03973236 -34.079692 3.426125e-21
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"Dimension of fractal:"}\NormalTok{,}\KeywordTok{signif}\NormalTok{(}\KeywordTok{summary}\NormalTok{(fit2)}\OperatorTok{$}\NormalTok{coeff[}\DecValTok{2}\NormalTok{],}\DecValTok{3}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Dimension of fractal: -1.35"
\end{verbatim}

So, the dimension is \(D_0\) = -1.35 \(\pm\) 0.04 for the one with the
anisotropy.

\hypertarget{results}{%
\section{Results}\label{results}}

Separetely, several fractals were generated, these are evaluated here
and summarized.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gd =}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\KeywordTok{file.path}\NormalTok{(path.results, master.result.file))}
\KeywordTok{plot}\NormalTok{(gd}\OperatorTok{$}\NormalTok{N, gd}\OperatorTok{$}\NormalTok{N.anisotropy, }\DataTypeTok{col=}\StringTok{'red'}\NormalTok{,}\DataTypeTok{pch=}\DecValTok{20}\NormalTok{, }\DataTypeTok{cex=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{report.fractal-dimensions_files/figure-latex/unnamed-chunk-8-1.pdf}

\hypertarget{appendix}{%
\section{Appendix}\label{appendix}}

Adding a few more things here. This report was generated in directory
/Users/gredigcsulb/Desktop/Fractal.

\hypertarget{speed}{%
\subsection{Speed}\label{speed}}

The larger the starting grid, the more time, here is a graph, of how
much time is expected for each computation:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gd =}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\KeywordTok{file.path}\NormalTok{(path.results, master.result.file))}
\NormalTok{gd}\OperatorTok{$}\NormalTok{anisotropy =}\StringTok{ }\KeywordTok{factor}\NormalTok{(gd}\OperatorTok{$}\NormalTok{N.anisotropy)}
\KeywordTok{ggplot}\NormalTok{(gd, }\KeywordTok{aes}\NormalTok{(N, generation.speed.sec, }\DataTypeTok{color=}\NormalTok{anisotropy)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{size=}\DecValTok{4}\NormalTok{,  }\DataTypeTok{alpha=}\FloatTok{0.8}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{'time (s)'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{'grid size N'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_log10}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_x_log10}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{report.fractal-dimensions_files/figure-latex/unnamed-chunk-9-1.pdf}

\hypertarget{solid-square}{%
\subsection{Solid Square}\label{solid-square}}

Some tests that we can do, a solid square should be 2D:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{q =}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DataTypeTok{ncol=}\DecValTok{100}\NormalTok{, }\DataTypeTok{nrow=}\DecValTok{100}\NormalTok{)}
\NormalTok{l2 =}\StringTok{ }\KeywordTok{get.fractal.dimension.boxing}\NormalTok{(q)}
\CommentTok{# returns Ne vs. e and fit}
\NormalTok{d =}\StringTok{ }\NormalTok{l2[[}\StringTok{'result'}\NormalTok{]]}
\KeywordTok{ggplot}\NormalTok{(d, }\KeywordTok{aes}\NormalTok{(e.inv.log, Ne.log)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{col=}\StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{'log (1/'}\NormalTok{,epsilon,}\StringTok{')'}\NormalTok{))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{'log (N'}\NormalTok{[epsilon],}\StringTok{')'}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{report.fractal-dimensions_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit =}\StringTok{ }\NormalTok{l2[[}\StringTok{'fit'}\NormalTok{]]}
\KeywordTok{summary}\NormalTok{(fit)}\OperatorTok{$}\NormalTok{coef}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Estimate Std. Error    t value     Pr(>|t|)
## (Intercept) -0.1607651 0.12462622  -1.289978 2.069140e-01
## e.inv.log   -1.9756604 0.04524407 -43.666725 1.031674e-28
\end{verbatim}

So, we find for a solid square, the dimension is \textbf{-1.98 \(\pm\)
0.05 dimensional}.

\hypertarget{solid-line}{%
\subsection{Solid Line}\label{solid-line}}

Some tests that we can do, a solid line should be 1D:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{q =}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DataTypeTok{ncol=}\DecValTok{100}\NormalTok{, }\DataTypeTok{nrow=}\DecValTok{100}\NormalTok{)}
\NormalTok{q[}\DecValTok{50}\NormalTok{,}\DecValTok{1}\OperatorTok{:}\DecValTok{100}\NormalTok{] =}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{100}\NormalTok{)}
\NormalTok{l2 =}\StringTok{ }\KeywordTok{get.fractal.dimension.boxing}\NormalTok{(q)}
\CommentTok{# returns Ne vs. e and fit}
\NormalTok{d =}\StringTok{ }\NormalTok{l2[[}\StringTok{'result'}\NormalTok{]]}
\KeywordTok{ggplot}\NormalTok{(d, }\KeywordTok{aes}\NormalTok{(e.inv.log, Ne.log)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{col=}\StringTok{'red'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{'log (1/'}\NormalTok{,epsilon,}\StringTok{')'}\NormalTok{))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\KeywordTok{expression}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{'log (N'}\NormalTok{[epsilon],}\StringTok{')'}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{report.fractal-dimensions_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit =}\StringTok{ }\NormalTok{l2[[}\StringTok{'fit'}\NormalTok{]]}
\KeywordTok{summary}\NormalTok{(fit)}\OperatorTok{$}\NormalTok{coef}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                Estimate Std. Error    t value     Pr(>|t|)
## (Intercept) -0.08038253 0.06231311  -1.289978 2.069140e-01
## e.inv.log   -0.98783018 0.02262203 -43.666725 1.031674e-28
\end{verbatim}

So, we find for a solid square, the dimension is \textbf{-0.988 \(\pm\)
0.02 dimensional}.


\end{document}
